name: Sync Resume from Overleaf

on:
  # schedule:
    # - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Overleaf project
        run: |
          git clone https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/${{secrets.PROJECT_ID}} resume

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
         root_file: resume/main.tex
         
      - name: Rename PDF
        run: mv resume/main.pdf resume/resume.pdf

      - name: Push PDF to GitHub
        run: |
          cp resume/resume.pdf .
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add resume.pdf
          git commit -m "Auto-update resume"
          git push
