permissions:
  contents: write

name: Sync Resume from Overleaf

on:
  # schedule:
    # - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Overleaf project
        run: |
          git clone https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/${{secrets.PROJECT_ID}} resume

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
         root_file: resume/main.tex

      - name: Debug files
        run: ls -R   
        
      - name: Moving PDF
        run: mv main.pdf ${{ github.workspace }}/resume.pdf

      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Ensure correct directory
        run: pwd && ls -a
        
      - name: Push PDF to GitHub
        # working-directory: ${{ github.workspace }}/resume/
        run: |
          pwd
          ls -R
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ${{ github.workspace }}/resume.pdf
          git commit -m "Auto-update resume"
          git push
