name: Sync Resume from Overleaf

on:
  # schedule:
    # - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Overleaf project
        run: |
          git clone https://git:${{ secrets.OVERLEAF_TOKEN }}@git.overleaf.com/${{secrets.Project_ID}} resume

      - name: Compile LaTeX
        run: |
          sudo apt-get install texlive-full -y
          cd resume
          latexmk -pdf resume.tex

      - name: Push PDF to GitHub
        run: |
          cp resume/resume.pdf .
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add resume.pdf
          git commit -m "Auto-update resume"
          git push
